spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/gram__test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: f11e89ca711ecc131d5ef5903bce49d8
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            google:
              client-id: 824196313175-olc6risfgpp042eggsdun6u36vr28ar3.apps.googleusercontent.com
              client-secret: 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
              redirect-uri: http://localhost:8080/login/oauth2/code/google
              token-uri: https://oauth2.googleapis.com/token
              resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
              scope:
                - profile
                - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: INFO
    com.ll.gramgram_ai: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
